### PR TITLE
#5 Improve tests

### PR DESCRIPTION
**Pull request by eltonnuness**
Hi Steve,

I removed the main of NewsGroupReader because the same test is made by you in src/it/java/... NewsClient.java

I am with difficult to create more tests, because some methods perform connections/showing gui or have too much dependency of other classes. The package (input) is a exemple. 

I do not know if some classes need refactor to the unit test be realized. Maybe I need more tools and expertise to create more, I bought the book  JUnit in Action 2nd Edition (Manning) to learn more about the tests.

I should have a capacity to analyse and verify if classes need refactor as a Unit Tester?

You can talk me if my difficulty is normal in your project ? Maybe because your project is somewhat old and the classes have much dependency between them (classes). Or because I am still to learning about tests?

---
This change is [Reviewable](https://reviewable.io/reviews/leonarduk/unison/77)

### CODE REVIEW

**Comment by leonarduk** [comment]
The code is old and not designed to be unit test friendly. Perhaps we need to rewrite the gui soon

**Comment by eltonnuness** [comment]
Right, I will try create more tests

**Comment by eltonnuness** [comment]
Yes later we go create a gui.

**Comment by eltonnuness** [comment]
the gui*

**Comment by leonarduk** [comment]
Looking into GUI tests tools,just now. Jubula seems to be one favoured by eclipse and works for swing and javafx

**Comment by eltonnuness** [comment]
Yes I saw the issue. Yes maybe is a good tool for us.

**Comment by eltonnuness** [comment]
Is a good pratice create an application to be friendly to unit tests?

**Comment by leonarduk** [comment]
Yes as automated tests allow us to make changes to code and catch bugs earlier

**Pull request merged**
