### PR TITLE
#8 - Improve the Gui [2]

### PR DESCRIPTION
**Pull request by eltonnuness**
This change is [Reviewable](https://reviewable.io/reviews/leonarduk/unison/121)

### CODE REVIEW

**Comment by leonarduk** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/java/uk/co/sleonard/unison/gui/generated/UNISoNTabbedFrameFX.java, line 1 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/121#-KKqZ83CfcjXXZyfQ_7q:-KKqZ83CfcjXXZyfQ_7r:-1908674397) ([raw file](https://github.com/leonarduk/unison/blob/953fa235ec2c358777e89188bf3783aa2a6b812c/src/main/java/uk/co/sleonard/unison/gui/generated/UNISoNTabbedFrameFX.java#L1)):*
> ```Java
> package uk.co.sleonard.unison.gui.generated;
> ```

Are these classes generated or manually created? If manual, package should be gui not gui.generated

---

*[src/main/java/uk/co/sleonard/unison/input/NewsGroupReader.java, line 11 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/121#-KKqZ_eebRH7InifPK4c:-KKqZ_eebRH7InifPK4d:1500374844) ([raw file](https://github.com/leonarduk/unison/blob/953fa235ec2c358777e89188bf3783aa2a6b812c/src/main/java/uk/co/sleonard/unison/input/NewsGroupReader.java#L11)):*
> ```Java
> import org.apache.log4j.Logger;
> 
> import uk.co.sleonard.unison.UNISoNController;
> ```

We shouldn't really have both versions of the controller and GUI.  Should only have the new one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/leonarduk/unison/121)*

**Comment by leonarduk** [comment]
Hi Elton, 

Looks promising progress.

Can you resolve the conflicts that are being reported please?  

Also, how is the unit testing going? Did you try that tool I found? I'd like you to develop tests as you develop the code not afterwards if possible.

Thanks
Steve

**Comment by eltonnuness** [comment]
Hi Steve,

Yes, we have promising progress.

Ok, I will resolve the conflicts.

I saw the Jubula Plugin and how it working, but I no create yet any call of method inside GUI, I still see how you initialize your program and passing this to JavaFX version, then next task is start to call methods in buttons, in this milestone I can start use the Jubula.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/java/uk/co/sleonard/unison/gui/generated/UNISoNTabbedFrameFX.java, line 1 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/121#-KKqZ83CfcjXXZyfQ_7q:-KKrqa8pwTn-i_jr8Jeh:-1590700044) ([raw file](https://github.com/leonarduk/unison/blob/953fa235ec2c358777e89188bf3783aa2a6b812c/src/main/java/uk/co/sleonard/unison/gui/generated/UNISoNTabbedFrameFX.java#L1)):*
<details><summary><i>Previously, leonarduk (Steve) wrote…</i></summary>
> Are these classes generated or manually created? If manual, package should be gui not gui.generated
</details>
Manual, I will change this

---

*[src/main/java/uk/co/sleonard/unison/input/NewsGroupReader.java, line 11 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/121#-KKqZ_eebRH7InifPK4c:-KKrqtG_fbg1OwURweB1:2053113640) ([raw file](https://github.com/leonarduk/unison/blob/953fa235ec2c358777e89188bf3783aa2a6b812c/src/main/java/uk/co/sleonard/unison/input/NewsGroupReader.java#L11)):*
<details><summary><i>Previously, leonarduk (Steve) wrote…</i></summary>
> We shouldn't really have both versions of the controller and GUI.  Should only have the new one
</details>
Really, I am still refactoring the classes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/leonarduk/unison/121#-:-KKrrcMKwSbwZQvXE5Gz:1103267684)*

**Comment by leonarduk** [comment]
Hi Elton, you can keep both versions of controller for the moment if you like if thats how you prefer to work until the first stable version is done

**Comment by eltonnuness** [comment]
Ok Steve.

Thank you!

**Comment by eltonnuness** [comment]
Steve,

I no understand where it is occurs the conflict, how I can view?

Thank you

**Comment by leonarduk** [comment]
Hi Elton,  I fixed the conflicts.  Can you pull this version of code and work from there?

Also, don't pull in any of my changes.  Please just work on your branch pushing to this one regularly.

Once its working we can merge it together

**Comment by eltonnuness** [comment]
Thanks for solve the conflicts.

Right, I will work from there!

Ok, Perfect!

**Pull request merged**
