### PR TITLE
Inserted comments and other adjustments 

### PR DESCRIPTION
**Pull request by eltonnuness**
This change is [Reviewable](https://reviewable.io/reviews/leonarduk/unison/62)

### CODE REVIEW

**Comment by leonarduk** [comment]
Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java, line 27 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK8jskVRrBeVimpTlZ:-KIK8jskVRrBeVimpTl_:-130814121) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java#L27)):*
> ```Java
>  * The Class DataQuery.
>  * 
>  * @author
> ```

if we add the @author tag we should put a name

---

*[src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java, line 29 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK8xLRtudCCTX1LUyo:-KIK8xLRtudCCTX1LUyp:1824505830) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java#L29)):*
> ```Java
>  * @author
>  * @since
>  *
> ```

we should add a value here. If not known, put v1.0.0

---

*[src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java, line 34 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK9BeS--NlljOSodVR:-KIK9BeS--NlljOSodVS:317005367) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java#L34)):*
> ```Java
> 
> 	/** The logger. */
> 	private static Logger			logger				= Logger.getLogger("DataQuery");
> ```

why are there tabs not spaces? can you check your eclipse settings?

---

*[src/main/java/uk/co/sleonard/unison/datahandling/HibernateHelper.java, line 77 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK9YzIaWOQL8fDzCm9:-KIK9YzJKiNkLyhVNXTQ:284732057) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/HibernateHelper.java#L77)):*
> ```Java
> 	private static boolean			firstConnect				= true;
> 
> 	/** The Constant GUI_ARGS. */
> ```

tabs should be space

---

*[src/main/java/uk/co/sleonard/unison/datahandling/UsenetUserHelper.java, line 10 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK9eSV0EPWSOxVkc0V:-KIK9eSV0EPWSOxVkc0W:-1830171193) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/UsenetUserHelper.java#L10)):*
> ```Java
>  * The Class UsenetUserHelper.
>  * 
>  * @author
> ```

need values

---

*[src/main/java/uk/co/sleonard/unison/datahandling/DAO/DownloadRequest.java, line 6 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK9mvANDTDdXHf-xXB:-KIK9mvANDTDdXHf-xXC:-1170138521) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/DAO/DownloadRequest.java#L6)):*
> ```Java
>  * The Class DownloadRequest.
>  * 
>  * @author
> ```

values

---

*[src/main/java/uk/co/sleonard/unison/datahandling/DAO/EmailAddress.java, line 6 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIK9uVzrZAAHQbOmnPt:-KIK9uVzrZAAHQbOmnPu:-1170138521) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/DAO/EmailAddress.java#L6)):*
> ```Java
>  * The Class EmailAddress.
>  * 
>  * @author
> ```

values

---

*[src/main/java/uk/co/sleonard/unison/datahandling/DAO/IpAddress.java, line 7 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIKA0udt0Vs5rmDuNlQ:-KIKA0udt0Vs5rmDuNlR:-1527802932) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/datahandling/DAO/IpAddress.java#L7)):*
> ```Java
>  * 
>  * @author Generated 11-Nov-2007 17:31:30 by Hibernate Tools 3.2.0.b9
>  * @since
> ```

date in since

---

*[src/main/java/uk/co/sleonard/unison/input/NewsArticle.java, line 268 \[r1\]](https://reviewable.io:443/reviews/leonarduk/unison/62#-KIKBQT9H0geb4_MOSZB:-KIKBQT9H0geb4_MOSZC:-137959066) ([raw file](https://github.com/leonarduk/unison/blob/62340b550817a2c96a7f029b8284ec16b85198dc/src/main/java/uk/co/sleonard/unison/input/NewsArticle.java#L268)):*
> ```Java
> 	 */
> 	public boolean isFullHeader() {
> 		return null == this.postingHost ? false : true;
> ```

why did you make this change some say ternary operator is bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/leonarduk/unison/62)*

**Comment by eltonnuness** [comment]
In author tags, I no have assurance what some classes were created by you. In the case is better remove @author, or you can put in the classes what you created ?

about spaces in variables, I am using your xml of configurations. maybe I no have configured properly, I will verify.

about ternary operator. The codacy says **"Avoid unnecessary if..then..else statements when returning booleans".** then I changed to ternary operator, but I can change to: 

return !(null == this.postingHost);

is better?

Thanks for comments Steve.
I need this!

**Comment by leonarduk** [comment]
Hi Elton, basically I wrote everything so I am the author. Where I copied it I put the author at the time.

**Comment by leonarduk** [comment]
Will reply to rest later

**Comment by leonarduk** [comment]
return (null != this.postingHost);

**Comment by leonarduk** [comment]
I have committed that change.

can you compare your settings with the ones put on the wiki?

**Comment by eltonnuness** [comment]
Ok, I will compare.

**Pull request merged**
