### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by leonarduk**
This change is [Reviewable](https://reviewable.io/reviews/leonarduk/unison/136)

### CODE REVIEW

**Comment by eltonnuness** [comment]
Oopps sorry, miss click in my Cell phone on close button.

**Comment by eltonnuness** [comment]
I receive e-mails about changes on Unison 😀 and I open to see. How are you Leonard?, You will back to update the project?

**Comment by leonarduk** [comment]
Hi Elton,

There were a whole pile of dependencies that I needed to update. Not looked at this in years. Considering doing some more stuff soon.

How are you doing.

**Comment by eltonnuness** [comment]
Hello,

Yeah, a lot of dependencies need updates.

I'm fine, working from home, and you ?

**Pull request closed without merging**
