### PR TITLE
Create helper method to convert string to date with java 8

### PR DESCRIPTION
**Pull request by eltonnuness**
#82 Done.

---
This change is [Reviewable](https://reviewable.io/reviews/leonarduk/unison/100)

### CODE REVIEW

**Comment by eltonnuness** [comment]
Wait Steve no merge, I will verify the error.

**Comment by leonarduk** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/uk/co/sleonard/unison/utils/StringUtils.java, line 221 \[r2\]](https://reviewable.io:443/reviews/leonarduk/unison/100#-KKAX6Np3h2f0Sz8xT7T:-KKAX6Nqgr7_hSEZT8VL:-287770046) ([raw file](https://github.com/leonarduk/unison/blob/f3df6f8505a84641cbb01892ae0d3b44e7727064/src/main/java/uk/co/sleonard/unison/utils/StringUtils.java#L221)):*
> ```Java
> 			try {
> 				// 20100101
> 				DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd");
> ```

Not all 8 char dates are yyyyMMdd could be ddMMyyyy or Americans might do MMddyyyy.  

---

*[src/main/java/uk/co/sleonard/unison/utils/StringUtils.java, line 239 \[r2\]](https://reviewable.io:443/reviews/leonarduk/unison/100#-KKAXaSY9xJFubw2zhzr:-KKAXaSZBiI-HHKubbTz:-785240065) ([raw file](https://github.com/leonarduk/unison/blob/f3df6f8505a84641cbb01892ae0d3b44e7727064/src/main/java/uk/co/sleonard/unison/utils/StringUtils.java#L239)):*
> ```Java
> 				throw new UNISoNException("Failed to parse date:" + text, e);
> 			}
> ```

could also have yyyy-MM-dd which is quite common too

---

*[src/main/resources/DB/projectDB.script, line 14 \[r2\]](https://reviewable.io:443/reviews/leonarduk/unison/100#-KKAYYihE_Nx1P_lNAeC:-KKAYYiil8UXtu1P7Fev:609158911) ([raw file](https://github.com/leonarduk/unison/blob/f3df6f8505a84641cbb01892ae0d3b44e7727064/src/main/resources/DB/projectDB.script#L14)):*
> ```
> ALTER TABLE MESSAGE ADD CONSTRAINT FK63B68BE78CB2634F FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(TOPIC_ID)
> ALTER TABLE NEWSGROUP_TOPIC ADD CONSTRAINT FKC76B3E7C8CB2634F FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(TOPIC_ID)
> ALTER TABLE IPADRESS ALTER COLUMN IP_ID RESTART WITH 1
> ```

Probably shouldnt have checked this one in

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/leonarduk/unison/100)*

**Comment by eltonnuness** [comment]
projectDB it is wrong commit, Disconsider, I will back to last file.

**Comment by eltonnuness** [comment]
The HttpDateObject apparently not cover all date masks, because of this I no create other covers of mask date., but I will try make this.

**Comment by leonarduk** [comment]
Hi Elton, other than those minor things it was a good commit, thanks.

**Comment by eltonnuness** [comment]
Hi Steve, Oh Right, Thanks

Steve I am with doubt how I will differentiate this two dates:

mask : ddMMyyyy
value : 01022016

mask : MMddyyyy
value : 02012016

How I can differentiate this in the my method, because I will receive any this values (american MMddyyyy or then ddMMyyyy).

**Comment by eltonnuness** [comment]
I create this to iterate to all formats:

symbols = { "dd", "MM", "yyyy" };

		for (int i = 0; i < symbols.length; i++) {
			for (int j = 0; j < symbols.length; j++) {
				for (int k = 0; k < symbols.length; k++) {
					if (i != j && i != k && j != k && k != i) {
						System.out.println(symbols[i] + symbols[j] + symbols[k]);
					}
				}
			}
		}
Output:
ddMMyyyy
ddyyyyMM
MMddyyyy
MMyyyydd
yyyyddMM
yyyyMMdd

but ddMMyyyy appears first that MMddyyyy, then 01022016 result in 01 Feb instead 02 Jan.

You think in any else to resolve this?

**Comment by leonarduk** [comment]
For date format. lets ignore American for now.

No point spending too long on it unless it becomes a problem.

Thanks

Steve

**Comment by eltonnuness** [comment]
Ok Steve, Thank you!

**Comment by eltonnuness** [comment]
Steve, you can saw my changes ?

**Comment by leonarduk** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/leonarduk/unison/100)*

**Comment by leonarduk** [comment]
Thanks Elton

**Comment by eltonnuness** [comment]
You're welcome!, Thank you by tips Steve.

**Pull request merged**
